name: Build and Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
  
    runs-on: windows-2022     

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
      
    - name: CMake Workflow
      shell: pwsh
      run: |
        cmake --preset x64-windows-clang
        cmake --build --preset x64-windows-clang-release
        ./build/Release/HelloClang.exe

    - name: Archive VCPKG Log Files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildlogs
        path: |
          vcpkg/buildtrees/*/*.txt
          vcpkg/buildtrees/*/*.log

    
